const COPY_FIRST = 'COPY_FIRST';
const COPY_LAST = 'COPY_LAST';
const REMOVE_ELEMENT = 'REMOVE_ELEMENT';
const VIEW_LIST = 'VIEW_LIST';
const VIEW_CARD = 'VIEW_CARD';

export {
   COPY_FIRST,
   COPY_LAST,
   REMOVE_ELEMENT,
   VIEW_LIST,
   VIEW_CARD
};